### ISSUE TITLE
Request support for SFOS 3.2.1

### ISSUE THREAD

**Issue by likeadragonmaid** [sailfishos-flatpak/main#14]
I would be nice if could get support for devices running sfos 3.2.1 if possible. When I try to install, it asks for missing dependency libstdc++.so.6

**Comment by rinigus** [comment]
It is supported, for now. But, you have to have device with newer libhybris than provided by 3.2.x and, to my knowledge, its limited to Sony Tama and FxPro1. 

Corresponding repo: https://build.merproject.org/project/show/home:rinigus:flatpak:3.2.1.20

Closing as there is support on flatpak side.

**Comment by likeadragonmaid** [comment]
I have required libhybris version but I still receive libstdc++ error.

**Comment by rinigus** [comment]
That is using 3.2. flatpak repository, not the regular one?

**Comment by likeadragonmaid** [comment]
Sorry, I was using latest repo instead of 3.2, thanks for help. It works fine now.

**Comment by rinigus** [comment]
Great, thanks for letting me know!
