### ISSUE TITLE
Telegram not working on Xperia X

### ISSUE THREAD

**Issue by marvinborner** [sailfishos-flatpak/main#16]
I followed your instructions and everything works perfectly, including the Angelfish browser.
When I execute `flatpak install --user org.telegram.desktop` however, it downloads for a minute or two and after a short glimpse of 100% I get a instant reboot (nothing wrong so far I guess, as this happened with Angelfish too).
After the reboot finished and I added the missing env variable, there is neither an icon in the drawer nor in the flatpak-runner. When I run `flatpak-runner org.telegram.desktop`, I get the following error:

`[D] unknown:0 - Using Wayland-EGL
Wayland socket: ../../display/wayland-1
WAYLAND_DISPLAY="../../display/wayland-1" FLATPAK_MALIIT_CONTAINER_DBUS="unix:abstract=/tmp/dbus-crWQATSq6g,guid=d753f7f45cf84171e67c1ac85ec6f7ee" flatpak run --env=QT_WAYLAND_FORCE_DPI=300 --filesystem=/system:ro --filesystem=/vendor:ro --filesystem=/odm:ro --device=all --talk-name=org.maliit.server --env=QTWEBENGINE_CHROMIUM_FLAGS=--disable-gpu-compositing --num-raster-threads=1 --enable-viewport --disable-composited-antialiasing --env=QTWEBENGINE_DISABLE_GPU_THREAD=1 --env=QT_QPA_PLATFORM=wayland --env=QT_QUICK_CONTROLS_MOBILE=1 --env=QT_QUICK_CONTROLS_STYLE=Plasma --env=HYBRIS_EGLPLATFORM_DIR=/usr/lib/arm-linux-gnueabihf/GL/host/lib/libhybris --env=HYBRIS_LINKER_DIR=/usr/lib/arm-linux-gnueabihf/GL/host/lib/libhybris/linker --env=HYBRIS_LD_LIBRARY_PATH=/usr/lib/arm-linux-gnueabihf/GL/host/libexec/droid-hybris/system/lib:/usr/libexec/droid-hybris/system/lib:/vendor/lib:/system/lib --env=LD_LIBRARY_PATH=/usr/lib/arm-linux-gnueabihf/GL/host/lib org.telegram.desktop
[D] onCompleted:424 - Warning: specifying an object instance for initialPage is sub-optimal - prefer to use a
Component
[W] unknown:53 - file:///usr/share/flatpak-runner/qml/main.qml:53:26: Unable to assign [undefined] to bool
error: app/org.telegram.desktop/arm/master not installed
[D] expression for onExit:59 - Skipping quit as it will hang the window. Proper exit is needed
`

The error message kinda says that it isn't installed at all and `flatpak run --user org.telegram.desktop` says the same, but `flatpak list` still says that the package is installed correctly and repairing/reinstalling/rebooting doesn't help either. All in all I'm very confused and a bit unsure whether the reboots may have caused a installation corruption. 
Anyways, thanks for your awesome work @rinigus, @CODeRUS and @ljo, I and the whole community really appreciate it!

## Further information
Kernel: `3.10.84`
Sailfish OS: `3.3.0.16`
Libhybris: `0.0.5.34`
Installed flatpaks according to `flatpak list`:
* org.freedesktop.Platform.GL.default
* org.freedesktop.Platform.ffmpeg-full
* org.kde.Platform
* org.kde.PlatformInputContexts.MaliitSailfishOS
* org.kde.mobile.angelfish
* org.telegram.desktop

**Comment by rinigus** [comment]
Have you tried to disable setuid on flatpak-bwrap? That way it should allow you to install cleanly. Also, run `flatpak repair --user` just in case

**Comment by marvinborner** [comment]
When I try to disable setuid on flatpak-bwrap with `devel-su chmod a-s /usr/libexec/flatpak-bwrap` the installation finally completes without reboots but I get the following error several times: `bwrap: Can't mount devpts on /newroot/dev/pts: Operation not permitted`, which seems kind of logical. The Telegram icon appears but it opens with errors. After multiple attempts with `flatpak install --user --reinstall org.telegram.desktop` and `flatpak repair --user`, it seems to work now and telegram successfully opens!

Although I don't exactly understand what was wrong and why the setuid removal fixed it, it worked and I'm happy - thanks!
