### ISSUE TITLE
FLATPAK installation

### ISSUE THREAD

**Issue by jophiel82** [sailfishos-flatpak/main#18]
Hello! I want to ask if it is possible to use Windows pc to install flatpak in sailfish os phone. Thank you in advance!

**Comment by rinigus** [comment]
Hi! Yes, sure. You can use Windows SSH client (one of the applications for logging into ssh servers) and login into your Sailfish phone on local wifi network. After that, all commands can be entered in ssh session

**Comment by rinigus** [comment]
Closing as its not really SFOS/Flatpak issue.
