### ISSUE TITLE
 I have used --user to install app but no enough space as well.

### ISSUE THREAD

**Issue by dashinfantry** [sailfishos-flatpak/main#19]
I have used --user to install app but no enough space as well. It's weird. It said there is only 500MB but I have much spare space.My system proportion is only 450MB spare,but other place has 35GB spare.Any reason?When I try to install angelfish and Libre office,  it shows space is not enough.

**Comment by rinigus** [comment]
I don't know how flatpak estimates the available space, unfortunately. Maybe there is a switch to disable it?

**Comment by dashinfantry** [comment]
fix it
