### ISSUE TITLE
F(x)tec Pro¹ support

### ISSUE THREAD

**Issue by Kabouik** [sailfishos-flatpak/main#4]
We are a couple Pro¹ SFOS users who would be keen to test Flatpak, since the keyboard would make a great combination with some Linux applications available as Flatpak, and remove some of the current limitations of using it on SFOS.

What would be required exactly to try this out? I have no coding skills and am a bit afraid this is out of my league, since I see we need to change kernel stuff and I have no idea how to do it. I hesitated between opening this issue here or on the [Pro¹ port](https://github.com/sailfish-on-fxtecpro1/droid-config-t5) repository, but figured it might be better to find information here and then maybe forward them to the skilled porters with a unit at hand there.

**Comment by rinigus** [comment]
There is a good chance that the namespace support is there already in Pro1. So, it maybe sufficient to recompile libhybris with https://github.com/libhybris/libhybris/pull/433 included. As Pro1 is at OBS, it is rather simple for porters.

**Comment by NotKit** [comment]
Angelfish works on Pro1 after building "tama" branch of libhybris with that change on OBS. It seems some changes will be needed to pass keyboard layout though.

**Comment by rinigus** [comment]
If we can get Sailfish keyboard supported that should resolve the keyboard layout issue as well.

**Comment by rinigus** [comment]
I presume its supported now. If it's not, please open an issue in Fxtec bug tracker to update libhybris
