### ISSUE TITLE
I can't install some apps

### ISSUE THREAD

**Issue by carmenfdezb** [sailfishos-flatpak/main#8]
Hi @rinigus !
I'm very happy to use flatpak in my Xperia XA2 since I updated SailfishOS to 3.3 yesterday. So thank you so much for your excellent work.
I've followed your instructions in [README](https://github.com/sailfishos-flatpak/main/blob/master/README.md) and installed angelfish, and at the moment everything works fine, maybe angelfish looks very big for me, but it works fine.
I would like to install kodi, this app is in flathub, but when I try to install it, I get an error: Nothing matches tv.kodi.Kodi in remote flathub.
Here it is a screenshot:
![Captura_20200403_001](https://user-images.githubusercontent.com/6286776/78355352-d6b1f400-75ad-11ea-95a8-a068435e18a4.png)
I have the same issue with Spotify. Am I doing something wrong or is it a bug?
Thank you for everything!

**Comment by rinigus** [comment]
Problem is that Kodi is x86 only: https://github.com/flathub/tv.kodi.Kodi/blob/master/flathub.json . I presume same is for Spotify. Hence we cannot install for ARM.

Re Angelfish size, I will update notes at TMO

**Comment by carmenfdezb** [comment]
Ok, thank for your quick answer!
I will close this issue :)

**Comment by rinigus** [comment]
FYI, I have added the corresponding text in README.md of this repository.
